// <auto-generated />
using System;
using IntroToOrms;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IntroToOrms.Migrations
{
    [DbContext(typeof(IntroToOrmsContext))]
    [Migration("20190318151506_AddedNonStringColumns")]
    partial class AddedNonStringColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("IntroToOrms.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AverageTicketPrice");

                    b.Property<int>("ChampionsWon");

                    b.Property<string>("City");

                    b.Property<string>("Coach");

                    b.Property<DateTime>("FoundedDate");

                    b.Property<string>("Mascot");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
